name: Quarkus Native Docker Build, Push, Deploy

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'

      - name: Set the incremental Docker image tag
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF:10}" >> $GITHUB_ENV
          env | sort

      - name: Build with Maven
        run: mvn -B -X package --file pom.xml -DskipTests 
         -Dquarkus.package.type=native
         -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-mandrel:22.3.0.1-Final-java17
         -Dquarkus.docker.dockerfile-native-path=src/main/docker/Dockerfile.native-micro
         -Dquarkus.native.container-build=true
         -Dquarkus.container-image.group=${{ secrets.DOCKERHUB_USERNAME }}
         -Dquarkus.container-image.tag=${{ env.RELEASE_VERSION }}
         -Dquarkus.container-image.username=${{ secrets.DOCKERHUB_USERNAME }}
         -Dquarkus.container-image.password=${{ secrets.DOCKERHUB_PASSWORD }}
         -Dquarkus.container-image.push=true
         -Dquarkus.kubernetes.replicas=4
         -Dquarkus.kubernetes-config.secrets=fstat
         -Dquarkus.kubernetes-config.secrets.enabled=true
         -Dquarkus.kubernetes.service-type=node-port
         -Dquarkus.kubernetes.node-port=32319
         -Dquarkus.kubernetes.part-of=fstat-app
         -Dquarkus.kubernetes.version=1.0.0
         -Dquarkus.kubernetes.name=fstat-srv
         -Dquarkus.kubernetes.resources.requests.memory=64Mi
         -Dquarkus.kubernetes.resources.requests.cpu=250m
         -Dquarkus.kubernetes.resources.limits.memory=128Mi
         -Dquarkus.kubernetes.resources.limits.cpu=500m

